### ISSUE TITLE
Composer dependency error

### ISSUE THREAD

**Issue by blipinsk** [matomo-org/github-sync#1]
Probably there is an error in `github-api` commit number.

Trying to call `composer install` results in `RuntimeException`.
To be more specific:

![zrzut ekranu 2015-04-10 o 14 59 47](https://cloud.githubusercontent.com/assets/6371716/7088204/4502d6ac-df92-11e4-86cb-5b4ab882c988.png)

**Comment by halfdan** [comment]
Hi @blipinsk! 
Thanks for your report. Above PR fixes the issue (we don't need to depend on the commit anymore).
